### ISSUE TITLE
Recursive Filtering

### ISSUE THREAD

**Issue by TrevorSlobodnick** [mklement0/fls#9]
Is there any way to implement recursive searching? I was hoping to use fls to list files in both the current directory and subdirectories, but it doesnt seem to be working. To list all files AND subdirectories in the current directory, I can use `ls -R`, and I thought I could use fls to change that to `fls f -R`, to show only the files. However it gives the same result as calling `fls f`. Is it possible to implement this functionality, or does it already exist and I'm just using it wrong?

**Comment by mklement0** [comment]
Good question.

Unfortunately, `fls` currently effectively ignores the `-R` option. Time permitting, I'll look into whether it's feasible to support it, though that sounds non-trivial. If not, I'll make use of `-R` an error.

**Comment by mklement0** [comment]
Unfortunately, supporting `-R` / `--recursive` would require much more effort that I'm willing to expend, so I've instead decided to disallow use of this option, and  the just-released version `0.4` now reports an error when you attempt to use it.
